import { useCallback, useEffect, useState } from "react";
import dayjs from "dayjs";
import { agentStatsApi } from "@/api/modules/agentStats";
import { chatApi } from "@/api/modules/chat";
import { cronJobApi } from "@/api/modules/cronjob";
import {
  llmOutputsApi,
  type LlmOutputItem,
} from "@/api/modules/llmOutputs";
import { skillApi } from "@/api/modules/skill";
import { toolsApi } from "@/api/modules/tools";
import { workspaceApi } from "@/api/modules/workspace";
import type { ChatSpec } from "@/api/types/chat";
import type { DailyStats } from "@/api/types/agentStats";
import type {
  CronExecutionHistoryItem,
  CronJobSpecOutput,
  CronJobState,
} from "@/api/types/cronjob";
import type { SkillSpec } from "@/api/types/skill";
import type { ToolInfo } from "@/api/modules/tools";
import type { DailyMemoryFile } from "@/api/types/workspace";
import {
  listAgentEditHistory,
  type AgentEditHistoryEvent,
} from "@/utils/agentEditHistoryStorage";

export type StatsRange = "day" | "week" | "month";

export type ScheduleJobRow = {
  id: string;
  name: string;
  description: string;
  plan: string;
  enabled: boolean;
  nextExec: string;
  executedCount: number;
  latestResult: string | null;
  status: "pending" | "completed" | "paused";
};

export type ScheduleRecordRow = {
  id: string;
  taskName: string;
  status: string;
  plannedTime: string;
  completedTime: string;
  result: string;
};

export type AgentDetailBundle = {
  loading: boolean;
  todayChats: number;
  totalChats: number;
  dailyStats: DailyStats[];
  rangeChats: number;
  skills: SkillSpec[];
  tools: ToolInfo[];
  /** Files generated by this agent (LLM outputs), used for「资料」. */
  generatedFiles: LlmOutputItem[];
  cronJobs: CronJobSpecOutput[];
  scheduleRows: ScheduleJobRow[];
  scheduleRecords: ScheduleRecordRow[];
  memories: DailyMemoryFile[];
  chats: ChatSpec[];
  editHistory: AgentEditHistoryEvent[];
  refreshHistory: () => void;
};

/** Load all LLM output pages then filter by agent_id (backend list has no agent filter). */
async function loadGeneratedFilesForAgent(
  agentId: string,
): Promise<LlmOutputItem[]> {
  const pageSize = 200;
  const first = await llmOutputsApi.list({ page: 1, page_size: pageSize });
  let items = first.items;
  if (first.items.length < first.total) {
    const totalPages = Math.ceil(first.total / pageSize);
    const rest = await Promise.all(
      Array.from({ length: totalPages - 1 }, (_, idx) =>
        llmOutputsApi.list({ page: idx + 2, page_size: pageSize }),
      ),
    );
    items = [...first.items, ...rest.flatMap((res) => res.items)];
  }
  return items.filter((item) => item.agent_id === agentId);
}

function formatDt(value?: string | null): string {
  if (!value) return "—";
  const d = dayjs(value);
  return d.isValid() ? d.format("YYYY/M/D HH:mm:ss") : value;
}

function rangeBounds(range: StatsRange, anchor: dayjs.Dayjs) {
  if (range === "week") {
    return {
      start: anchor.startOf("week").format("YYYY-MM-DD"),
      end: anchor.endOf("week").format("YYYY-MM-DD"),
    };
  }
  if (range === "month") {
    return {
      start: anchor.startOf("month").format("YYYY-MM-DD"),
      end: anchor.endOf("month").format("YYYY-MM-DD"),
    };
  }
  const day = anchor.format("YYYY-MM-DD");
  return { start: day, end: day };
}

async function loadSchedule(
  agentId: string,
  jobs: CronJobSpecOutput[],
): Promise<{
  rows: ScheduleJobRow[];
  records: ScheduleRecordRow[];
}> {
  const enriched = await Promise.all(
    jobs.map(async (job) => {
      let state: CronJobState = {};
      let history: CronExecutionHistoryItem[] = [];
      try {
        const view = await cronJobApi.getCronJob(job.id, agentId);
        state = view.state ?? {};
      } catch {
        /* ignore */
      }
      try {
        history = await cronJobApi.listJobHistory(job.id, agentId);
      } catch {
        history = [];
      }
      const latest = history[0];
      const enabled = job.enabled !== false;
      const status: ScheduleJobRow["status"] = !enabled
        ? "paused"
        : latest?.status === "success"
          ? "completed"
          : "pending";
      const row: ScheduleJobRow = {
        id: job.id,
        name: job.name || job.id,
        description:
          typeof job.text === "string"
            ? job.text
            : typeof job.request?.input === "string"
              ? job.request.input
              : "",
        plan: job.schedule?.cron ? `cron: ${job.schedule.cron}` : "—",
        enabled,
        nextExec: formatDt(state.next_run_at),
        executedCount: history.length,
        latestResult: latest?.status ?? null,
        status,
      };
      const records: ScheduleRecordRow[] = history.map((h, idx) => ({
        id: `${job.id}-${idx}-${h.run_at}`,
        taskName: job.name || job.id,
        status: h.status,
        plannedTime: formatDt(h.run_at),
        completedTime: formatDt(h.run_at),
        result: h.error || h.status,
      }));
      return { row, records };
    }),
  );

  return {
    rows: enriched.map((e) => e.row),
    records: enriched
      .flatMap((e) => e.records)
      .sort((a, b) => b.plannedTime.localeCompare(a.plannedTime)),
  };
}

export function useAgentDetailData(
  agentId: string | null,
  open: boolean,
  statsRange: StatsRange,
  anchorDate: dayjs.Dayjs,
): AgentDetailBundle {
  const [loading, setLoading] = useState(false);
  const [todayChats, setTodayChats] = useState(0);
  const [totalChats, setTotalChats] = useState(0);
  const [dailyStats, setDailyStats] = useState<DailyStats[]>([]);
  const [rangeChats, setRangeChats] = useState(0);
  const [skills, setSkills] = useState<SkillSpec[]>([]);
  const [tools, setTools] = useState<ToolInfo[]>([]);
  const [generatedFiles, setGeneratedFiles] = useState<LlmOutputItem[]>([]);
  const [cronJobs, setCronJobs] = useState<CronJobSpecOutput[]>([]);
  const [scheduleRows, setScheduleRows] = useState<ScheduleJobRow[]>([]);
  const [scheduleRecords, setScheduleRecords] = useState<ScheduleRecordRow[]>(
    [],
  );
  const [memories, setMemories] = useState<DailyMemoryFile[]>([]);
  const [chats, setChats] = useState<ChatSpec[]>([]);
  const [editHistory, setEditHistory] = useState<AgentEditHistoryEvent[]>([]);

  const refreshHistory = useCallback(() => {
    if (!agentId) {
      setEditHistory([]);
      return;
    }
    setEditHistory(listAgentEditHistory(agentId));
  }, [agentId]);

  useEffect(() => {
    if (!open || !agentId) return;

    let cancelled = false;
    setLoading(true);
    refreshHistory();

    const today = dayjs().format("YYYY-MM-DD");
    const { start, end } = rangeBounds(statsRange, anchorDate);
    const totalStart = dayjs().subtract(365, "day").format("YYYY-MM-DD");

    (async () => {
      const [
        todayStatsRes,
        rangeStatsRes,
        totalStatsRes,
        skillsRes,
        toolsRes,
        generatedRes,
        jobsRes,
        memoryRes,
        chatsRes,
      ] = await Promise.allSettled([
        agentStatsApi.getAgentStats(
          { start_date: today, end_date: today },
          agentId,
        ),
        agentStatsApi.getAgentStats(
          { start_date: start, end_date: end },
          agentId,
        ),
        agentStatsApi.getAgentStats(
          { start_date: totalStart, end_date: today },
          agentId,
        ),
        skillApi.listSkills(agentId),
        toolsApi.listTools(agentId),
        loadGeneratedFilesForAgent(agentId),
        cronJobApi.listCronJobs(agentId),
        workspaceApi.listDailyMemory(agentId),
        chatApi.listChats(undefined, agentId),
      ]);

      if (cancelled) return;

      const todayStats =
        todayStatsRes.status === "fulfilled" ? todayStatsRes.value : null;
      const rangeStats =
        rangeStatsRes.status === "fulfilled" ? rangeStatsRes.value : null;
      const totalStats =
        totalStatsRes.status === "fulfilled" ? totalStatsRes.value : null;
      const skillList =
        skillsRes.status === "fulfilled" ? skillsRes.value : [];
      const toolList = toolsRes.status === "fulfilled" ? toolsRes.value : [];
      const generated =
        generatedRes.status === "fulfilled" ? generatedRes.value : [];
      const jobs = jobsRes.status === "fulfilled" ? jobsRes.value : [];
      const mems = memoryRes.status === "fulfilled" ? memoryRes.value : [];
      const chatList = chatsRes.status === "fulfilled" ? chatsRes.value : [];

      const todayChatsCount =
        todayStats?.by_date?.reduce((s, d) => s + (d.chats || 0), 0) ??
        chatList.filter((c) => c.created_at?.startsWith(today)).length;
      const totalChatsCount =
        totalStats?.by_date?.reduce((s, d) => s + (d.chats || 0), 0) ??
        chatList.length;
      const rangeChatsCount =
        rangeStats?.by_date?.reduce((s, d) => s + (d.chats || 0), 0) ?? 0;

      setTodayChats(todayChatsCount);
      setTotalChats(totalChatsCount);
      setRangeChats(rangeChatsCount);
      setDailyStats(rangeStats?.by_date ?? []);
      setSkills(Array.isArray(skillList) ? skillList : []);
      setTools(Array.isArray(toolList) ? toolList.filter((t) => t.enabled) : []);
      setGeneratedFiles(Array.isArray(generated) ? generated : []);
      setCronJobs(Array.isArray(jobs) ? jobs : []);
      setMemories(Array.isArray(mems) ? mems : []);
      setChats(
        Array.isArray(chatList)
          ? [...chatList].sort((a, b) =>
              (b.updated_at ?? "").localeCompare(a.updated_at ?? ""),
            )
          : [],
      );

      if (Array.isArray(jobs) && jobs.length > 0) {
        const schedule = await loadSchedule(agentId, jobs);
        if (!cancelled) {
          setScheduleRows(schedule.rows);
          setScheduleRecords(schedule.records);
        }
      } else {
        setScheduleRows([]);
        setScheduleRecords([]);
      }
    })()
      .catch(() => {
        /* keep previous */
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, [open, agentId, statsRange, anchorDate, refreshHistory]);

  return {
    loading,
    todayChats,
    totalChats,
    dailyStats,
    rangeChats,
    skills,
    tools,
    generatedFiles,
    cronJobs,
    scheduleRows,
    scheduleRecords,
    memories,
    chats,
    editHistory,
    refreshHistory,
  };
}
